import { AuthProvider } from '@/components/auth-provider/AuthProvider';
import { Header } from '@/components/Header/Header';
import { montserrat, roboto } from '@/fonts';
import { availableLocales, LocaleTypes } from '@/utils/i18n';
import '@fortawesome/fontawesome-svg-core/styles.css';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return availableLocales.map((locale) => ({
    locale,
  }));
}

export type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: LocaleTypes };
};

export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header locale={locale} />
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
